spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/spring
    username: admin
    password: password

  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB

  mvc:
    async:
      request-timeout: 3600000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

cloud:
  aws:
    s3:
      bucket: drive-dya
    region:
      static: ap-northeast-2
    credentials:
      accessKey: AKIAZS3VJIUWZ2QRG4FD
      secretKey: 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